# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |server|
    config.vm.define server["name"] do |srv|
      srv.vm.hostname = server["name"]
      srv.vm.box = server["box"]
      srv.vm.network "private_network", ip: server["ip"]
      srv.vm.provider :libvirt do |libvirt|
        libvirt.qemu_use_session = false
        libvirt.cpus = server["cpu"]
        libvirt.memory = server["ram"]
      end
      # TODO: fix SSH config via bastion
      if server["name"] != "bastion"
        srv.ssh.host = server["ip"]
        srv.ssh.extra_args = ["-vvv", "-A", "-J", "vagrant@10.0.0.111"]
        srv.ssh.forward_agent = true
        srv.ssh.extra_args = ["-o", "ProxyCommand='ssh -A -i .vagrant/machines/bastion/libvirt/private_key -l vagrant 10.0.0.111 -W %h:%p '"]
        srv.ssh.proxy_command = "ssh vagrant@10.0.0.111 -i .vagrant/machines/bastion/libvirt/private_key -W %h:%p"
      end
      # srv.ssh.insert_key = false
      # if File.exist? ".vagrant/machines/#{server['name']}/flag"
      #   srv.ssh.host = server["ip"]
      #   srv.ssh.password = "vagrant"
      #   if server["name"] != "bastion"
      #     srv.ssh.extra_args = ["-vvv", "-A", "-J", "vagrant@10.0.0.111"]
      #   end
      # end
      # Provisioners
      srv.vm.provision "shell", path: "scripts/script_bootstrap.sh"
      if server["name"] == "lb-web"
        srv.vm.provision "shell", path: "scripts/script_lb-web.sh"
      elsif server["name"].start_with?('web')
        srv.vm.provision "shell", path: "scripts/script_web.sh"
      end
      srv.vm.provision "shell", path: "scripts/script_firewall.sh"
      # srv.trigger.after :up do |trigger|
      #   trigger.info = "More information"
      #   trigger.run = {inline: "bash -c \"echo 'firewall applied' > .vagrant/machines/#{server['name']}/flag\""}
      # end
    end
  end
end
