---
- hosts: vms
  gather_facts: true
  become: true
  tasks: 
    - debug:
        msg: "Hello"
    # - debug:
    #     var: hostvars[inventory_hostname]
    - name: Install the latest version of python3
      ansible.builtin.yum:
        name: python3-yum
        state: latest
    - name: Install the latest version of Vim
      ansible.builtin.yum:
        name: vim
        state: latest
