---
all:
  vars:
    ansible_user: jakubpospieszny
    ansible_password: q1w2e3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:

    hypervisors:
      children:
        desktophp:
          hosts:
            desktophp1:
              ansible_host: 10.0.0.1

          children:
            vms:
              vars: 
                ansible_user: vagrant
                ansible_password: vagrant
                ansible_ssh_private_key_file: ~/Documents/Miki/examples/vagrant_haproxy_tcp_nginx/.vagrant/machines/{{ ssh_vagrant_hostname }}/libvirt/private_key
                ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q vagrant@10.0.0.111 -i ~/Documents/Miki/examples/vagrant_haproxy_tcp_nginx/.vagrant/machines/Bastion/libvirt/private_key"'
              children:
                webservers:
                  hosts:
                    web1.kobeeq.eu:
                      ssh_vagrant_hostname: Web-1
                      ansible_host: 10.0.0.21
                    web2.kobeeq.eu:
                      ssh_vagrant_hostname: Web-2
                      ansible_host: 10.0.0.22

                loadbalancers:
                  hosts:
                    weblb.kobeeq.eu:
                      ssh_vagrant_hostname: Web-lb
                      ansible_host: 10.0.0.11
                
                dnsservers:
                  hosts:
                    bind.kobeeq.eu:
                      ssh_vagrant_hostname: Bind
                      ansible_host: 10.0.0.23
                
                bastions:
                  hosts:
                    bastion.kobeeq.eu:
                      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
                      ssh_vagrant_hostname: Bastion
                      ansible_host: 10.0.0.111

