# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yaml')

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.hostname = servers["name"]
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider :libvirt do |libvirt|
        libvirt.qemu_use_session = false
        libvirt.cpus = servers["cpu"]
        libvirt.memory = servers["ram"]
        libvirt.nested = true
        libvirt.cpu_mode = "host-passthrough"
      end
      if servers["name"]== "web-lb"
        srv.vm.provision "shell", path: "script_web-lb.sh"
      elsif servers["name"].start_with?('web' ,'Web') && servers["name"] != "web-lb"
        srv.vm.provision "shell", path: "script_web.sh"
      else
        put "None script is going to start."
      end
    end
  end
end
